name: "Notebook Cleaner"
description: "Remove interactive widget outputs from Jupyter/Colab notebooks and replace with a placeholder + Colab link."
author: "Jan Zika"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Run notebook cleaner
      run: python $GITHUB_ACTION_PATH/clean_notebooks.py .
      shell: bash
      env:
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
