name: Clean Jupyter Notebooks

on:
  push:
    paths:
      - "**/*.ipynb"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install nbformat
        run: pip install nbformat

      - name: Clean notebooks
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "Cleaning $nb"
            python .github/scripts/clean_notebook.py "$nb"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clean notebooks [skip ci]"
          file_pattern: "*.ipynb"
